// <auto-generated />
using System;
using EnergyX.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace EnergyX.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241117223838_EnergyX_MigrationV3_UpdateTblTurnos")]
    partial class EnergyX_MigrationV3_UpdateTblTurnos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EnergyX.Models.HistoricoRelatorio", b =>
                {
                    b.Property<long>("HistRelatorioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("hist_relatorio_id");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("HistRelatorioId"));

                    b.Property<DateTime>("DataHoraAtualizacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("data_hora_atualizacao");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("observacoes");

                    b.Property<long>("RelatorioTurnoId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("relatorio_turno_id");

                    b.HasKey("HistRelatorioId");

                    b.HasIndex("RelatorioTurnoId");

                    b.ToTable("gs_el_historico_relatorio", (string)null);
                });

            modelBuilder.Entity("EnergyX.Models.LocalizacaoReator", b =>
                {
                    b.Property<long>("LocReatorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("loc_reator_id");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("LocReatorId"));

                    b.Property<string>("Descricao")
                        .HasMaxLength(250)
                        .HasColumnType("NVARCHAR2(250)")
                        .HasColumnName("descricao");

                    b.Property<string>("Setor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("setor");

                    b.Property<string>("Unidade")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("unidade");

                    b.HasKey("LocReatorId");

                    b.ToTable("gs_el_localizacao_reator", (string)null);
                });

            modelBuilder.Entity("EnergyX.Models.Operadores", b =>
                {
                    b.Property<long>("OperadorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("operador_id");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("OperadorId"));

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("cargo");

                    b.Property<string>("Lor")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("lor");

                    b.Property<string>("NomeOperador")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("nome_operador");

                    b.Property<string>("SenhaOperador")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("senha_operador");

                    b.Property<long>("TurnoId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("turno_id");

                    b.HasKey("OperadorId");

                    b.HasIndex("TurnoId");

                    b.ToTable("gs_el_operadores", (string)null);
                });

            modelBuilder.Entity("EnergyX.Models.Reatores", b =>
                {
                    b.Property<long>("ReatorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("reator_id");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ReatorId"));

                    b.Property<long>("LocalizacaoReatorId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("loc_reator_id");

                    b.Property<string>("NomeReator")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("nome_reator");

                    b.Property<long>("PressaoMax")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("pressao_max");

                    b.Property<long>("RadiacaoMax")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("radiacao_max");

                    b.Property<long>("TemperaturaMax")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("temperatura_max");

                    b.Property<long>("TipoReatorId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("tipo_reator_id");

                    b.HasKey("ReatorId");

                    b.HasIndex("LocalizacaoReatorId");

                    b.HasIndex("TipoReatorId");

                    b.ToTable("gs_el_reatores", (string)null);
                });

            modelBuilder.Entity("EnergyX.Models.RelatoriosTurno", b =>
                {
                    b.Property<long>("RelatorioTurnoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("relatorio_turno_id");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RelatorioTurnoId"));

                    b.Property<DateTime>("DataHoraRelatorio")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("data_hora_relatorio");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(300)
                        .HasColumnType("NVARCHAR2(300)")
                        .HasColumnName("observacoes");

                    b.Property<long>("OperadorId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("operador_id");

                    b.Property<long>("ReatorId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("reator_id");

                    b.Property<string>("ResumoAtividades")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("resumo_atividades");

                    b.HasKey("RelatorioTurnoId");

                    b.HasIndex("OperadorId");

                    b.HasIndex("ReatorId");

                    b.ToTable("gs_el_relatorios_turno", (string)null);
                });

            modelBuilder.Entity("EnergyX.Models.TipoReator", b =>
                {
                    b.Property<long>("TipoReatorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("tipo_reator_id");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TipoReatorId"));

                    b.Property<long>("CapacidadeEnergia")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("capacidade_energia");

                    b.Property<string>("DescricaoReator")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("descricao_reator");

                    b.Property<string>("Fabricante")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("fabricante");

                    b.Property<string>("Tecnologia")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("tecnologia");

                    b.HasKey("TipoReatorId");

                    b.ToTable("gs_el_tipo_reator", (string)null);
                });

            modelBuilder.Entity("EnergyX.Models.Turnos", b =>
                {
                    b.Property<long>("TurnoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("turno_id");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TurnoId"));

                    b.Property<string>("DescricaoTurno")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("descricao_turno");

                    b.HasKey("TurnoId");

                    b.ToTable("gs_el_turnos", (string)null);
                });

            modelBuilder.Entity("EnergyX.Models.HistoricoRelatorio", b =>
                {
                    b.HasOne("EnergyX.Models.RelatoriosTurno", "RelatorioTurno")
                        .WithMany()
                        .HasForeignKey("RelatorioTurnoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("gs_el_relatorios_turno_fk");

                    b.Navigation("RelatorioTurno");
                });

            modelBuilder.Entity("EnergyX.Models.Operadores", b =>
                {
                    b.HasOne("EnergyX.Models.Turnos", "Turno")
                        .WithMany()
                        .HasForeignKey("TurnoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("gs_el_turnos_fk");

                    b.Navigation("Turno");
                });

            modelBuilder.Entity("EnergyX.Models.Reatores", b =>
                {
                    b.HasOne("EnergyX.Models.LocalizacaoReator", "LocalizacaoReator")
                        .WithMany()
                        .HasForeignKey("LocalizacaoReatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("gs_el_localizacao_reator_fk");

                    b.HasOne("EnergyX.Models.TipoReator", "TipoReator")
                        .WithMany()
                        .HasForeignKey("TipoReatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("gs_el_tipo_reator_fk");

                    b.Navigation("LocalizacaoReator");

                    b.Navigation("TipoReator");
                });

            modelBuilder.Entity("EnergyX.Models.RelatoriosTurno", b =>
                {
                    b.HasOne("EnergyX.Models.Operadores", "Operador")
                        .WithMany()
                        .HasForeignKey("OperadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("gs_el_operadores_fk");

                    b.HasOne("EnergyX.Models.Reatores", "Reator")
                        .WithMany()
                        .HasForeignKey("ReatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("gs_el_reatores_fk");

                    b.Navigation("Operador");

                    b.Navigation("Reator");
                });
#pragma warning restore 612, 618
        }
    }
}
